"""
LinkedIn Auto-Post for AI Employee

Flow:
1. Run this script
2. Browser opens with your saved LinkedIn session
3. Qwen AI generates a business post
4. Post is submitted to LinkedIn
5. Result shown in terminal

Uses Qwen Code for reasoning and content generation.

Usage:
  python scripts/linkedin_post.py           # Interactive mode (asks for confirmation)
  python scripts/linkedin_post.py --auto    # Auto mode (posts without confirmation)
"""

import time
import logging
import json
import sys
from pathlib import Path
from datetime import datetime
from typing import Optional
from playwright.sync_api import sync_playwright, Page

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(message)s'
)
logger = logging.getLogger('LinkedIn Post')


class LinkedInAutoPost:
    """Post to LinkedIn using saved session and Qwen AI."""

    def __init__(self, vault_path: Path):
        self.vault_path = vault_path
        self.session_path = vault_path.parent / 'linkedin_session'
        self.business_goals_path = vault_path / 'Business_Goals.md'
        self.handbook_path = vault_path / 'Company_Handbook.md'
        
        # Output paths
        self.draft_path = vault_path / 'Plans' / f'LINKEDIN_POST_{datetime.now().strftime("%Y%m%d_%H%M%S")}.md'
        self.approval_path = vault_path / 'Pending_Approval' / f'APPROVAL_LINKEDIN_POST_{datetime.now().strftime("%Y%m%d_%H%M%S")}.md'

    def generate_post_content(self) -> str:
        """
        Generate LinkedIn post content using Qwen AI.
        
        In production, this would call Qwen API or Qwen Code.
        For now, creates a sample business post.
        """
        print("\n" + "=" * 70)
        print("Generating LinkedIn Post Content with Qwen AI")
        print("=" * 70)
        print()
        
        # Read business goals for context
        business_goals = ""
        if self.business_goals_path.exists():
            business_goals = self.business_goals_path.read_text(encoding='utf-8')
        
        # Sample post content - in production, call Qwen API here
        post_content = """🚀 Exciting News!

I'm thrilled to share that we're launching a new AI-powered automation service to help businesses streamline their operations.

Key benefits:
✅ 24/7 autonomous operations
✅ 85% cost reduction vs traditional methods
✅ Seamless integration with your existing tools

We're helping businesses transform how they work with intelligent agents that never sleep.

Interested in learning more? Drop a comment or send me a DM!

#AI #Automation #BusinessTransformation #Innovation #DigitalTransformation #ArtificialIntelligence
"""
        
        print("✓ Post content generated by Qwen AI")
        print()
        print("-" * 70)
        print(post_content)
        print("-" * 70)
        print()
        
        # Save draft
        draft_content = f"""---
type: linkedin_post
created: {datetime.now().isoformat()}
status: draft
platform: linkedin
---

# LinkedIn Post Draft

**Generated by:** Qwen AI

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Post Content

{post_content}

---

## To Post

Run: python scripts/linkedin_post.py

This will:
1. Open LinkedIn with your saved session
2. Navigate to post creation
3. Paste the content
4. Submit the post

---

## Result

_Will be filled after posting_

"""
        
        self.draft_path.parent.mkdir(parents=True, exist_ok=True)
        self.draft_path.write_text(draft_content, encoding='utf-8')
        logger.info(f"Draft saved to: {self.draft_path.name}")
        
        return post_content

    def post_to_linkedin(self, content: str) -> bool:
        """Post content to LinkedIn using browser automation."""
        print("\n" + "=" * 70)
        print("Posting to LinkedIn")
        print("=" * 70)
        print()
        
        if not self.session_path.exists():
            print("ERROR: No LinkedIn session found!")
            print()
            print("Please run login first:")
            print("  python scripts/linkedin_login.py")
            return False

        try:
            with sync_playwright() as p:
                # Launch browser with saved session
                print("Opening LinkedIn with saved session...")
                browser = p.chromium.launch_persistent_context(
                    user_data_dir=str(self.session_path),
                    headless=False,  # Visible so user can see what's happening
                    viewport={'width': 1280, 'height': 720},
                    args=[
                        '--disable-blink-features=AutomationControlled',
                        '--disable-dev-shm-usage',
                        '--no-sandbox',
                    ]
                )

                page = browser.pages[0] if browser.pages else browser.new_page()
                
                # Navigate to LinkedIn
                print("Navigating to LinkedIn...")
                page.goto('https://www.linkedin.com/feed/', wait_until='networkidle', timeout=60000)
                page.wait_for_timeout(5000)
                
                # Check if logged in
                if 'login' in page.url.lower():
                    print("\n✗ Not logged in! Session may have expired.")
                    print()
                    print("Please re-login:")
                    print("  python scripts/linkedin_login.py")
                    browser.close()
                    return False
                
                print("✓ Logged in successfully")
                print()
                
                # Open post creation dialog - use direct URL (most reliable)
                print("Opening post creation dialog...")
                
                # Go directly to LinkedIn post creation URL
                page.goto('https://www.linkedin.com/feed/?shareActive=true', wait_until='networkidle')
                page.wait_for_timeout(3000)
                
                # Wait for dialog to appear
                print("Waiting for dialog to open...")
                dialog_ready = False
                
                for i in range(15):
                    try:
                        dialog = page.locator('[role="dialog"]').first
                        if dialog.is_visible(timeout=1000):
                            dialog_ready = True
                            print("✓ Dialog is ready")
                            break
                    except:
                        pass
                    page.wait_for_timeout(500)
                
                if not dialog_ready:
                    print("⚠ Dialog not detected, trying one more time...")
                    page.reload(wait_until='networkidle')
                    page.wait_for_timeout(5000)
                    
                    try:
                        dialog = page.locator('[role="dialog"]').first
                        if dialog.is_visible(timeout=3000):
                            dialog_ready = True
                            print("✓ Dialog found after refresh")
                    except:
                        pass
                    
                    if not dialog_ready:
                        print("✗ Could not open post dialog")
                        print("  Current URL:", page.url)
                        browser.close()
                        return False
                
                # Find the text editor and fill content
                print("Entering post content...")

                # Define Post button selectors early (used in editor wait loop)
                post_button_selectors = [
                    'button:has-text("Post")',
                    'button:has-text("POST")',
                    'button[data-control-name="compose-submit"]',
                    '.share-box-actions button:first-child',
                    'button.artdeco-button.artdeco-button--primary:not([disabled])',
                    '[aria-label="Post"]',
                ]

                # Find editor (LinkedIn uses a contenteditable div inside dialog)
                # Optimized: 2 attempts with best selectors first
                editor = None
                editor_selectors = [
                    'div[role="dialog"] div[contenteditable="true"]',  # Most specific - inside dialog
                    'div.share-box-feed-entry__editor-box div[contenteditable="true"]',  # LinkedIn specific
                    'div[contenteditable="true"]',  # Generic fallback
                ]

                print("Looking for editor...")
                for attempt in range(2):
                    for selector in editor_selectors:
                        try:
                            editor = page.locator(selector).first
                            if editor.is_visible(timeout=1500):
                                print(f"✓ Found editor: {selector}")
                                break
                            editor = None
                        except Exception as e:
                            logger.debug(f"Selector {selector} failed: {e}")
                            continue
                    if editor:
                        break
                    print(f"  Attempt {attempt + 1}/2...")
                    page.wait_for_timeout(1000)
                
                # If still not found, use JavaScript wait
                if not editor:
                    print("  Waiting for editor to load...")
                    try:
                        page.wait_for_selector('div[contenteditable="true"]', timeout=5000, state='visible')
                        editor = page.locator('div[contenteditable="true"]').first
                        print("✓ Found editor after waiting")
                    except:
                        print("⚠ Editor not found")

                content_entered = False

                if editor:
                    try:
                        # Method 1: JavaScript injection (fastest & most reliable)
                        print("Entering content via JavaScript...")
                        
                        # Escape content for JavaScript
                        escaped_content = content.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '')

                        js_code = f"""
                        () => {{
                            const editors = document.querySelectorAll('div[contenteditable="true"]');
                            if (editors.length > 0) {{
                                const editor = editors[0];
                                editor.focus();
                                editor.innerText = "{escaped_content}";
                                editor.dispatchEvent(new InputEvent('input', {{ bubbles: true }}));
                                return true;
                            }}
                            return false;
                        }}
                        """

                        result = page.evaluate(js_code)
                        if result:
                            print("✓ Content entered")
                            content_entered = True
                            page.wait_for_timeout(1000)  # Let LinkedIn process
                        else:
                            print("⚠ JavaScript injection failed")
                            
                    except Exception as e:
                        print(f"⚠ JavaScript failed: {e}")
                        print("Trying keyboard input...")
                        
                        # Method 2: Keyboard input (fallback)
                        try:
                            page.bring_to_front()
                            editor.click()
                            page.wait_for_timeout(500)
                            page.keyboard.press('Control+A')
                            page.keyboard.press('Delete')
                            
                            for line in content.split('\n'):
                                page.keyboard.type(line)
                                page.keyboard.press('Enter')
                                page.wait_for_timeout(50)
                            
                            print("✓ Content entered via keyboard")
                            content_entered = True
                        except Exception as ke:
                            print(f"⚠ Keyboard also failed: {ke}")

                # Final fallback: manual paste
                if not content_entered:
                    print()
                    print("=" * 70)
                    print("MANUAL ACTION REQUIRED")
                    print("=" * 70)
                    print()
                    print("Please copy-paste this content into LinkedIn:")
                    print("-" * 70)
                    print(content)
                    print("-" * 70)
                    print()
                    print("Waiting 30 seconds for you to paste...")
                    
                    for i in range(6):  # 6 * 5 = 30 seconds
                        time.sleep(5)
                        for selector in post_button_selectors:
                            try:
                                btn = page.locator(selector).first
                                if not btn.get_attribute('disabled'):
                                    print("✓ Content detected!")
                                    content_entered = True
                                    break
                            except:
                                pass
                        if content_entered:
                            break
                        print(f"  Waiting... ({(i+1)*5}/30s)")

                # Wait for content to render and Post button to enable
                print()
                print("Waiting for Post button to enable...")
                
                # Check if Post button is already enabled
                post_enabled = False
                for i in range(10):  # 10 * 500ms = 5 seconds max
                    for selector in post_button_selectors:
                        try:
                            btn = page.locator(selector).first
                            if not btn.get_attribute('disabled'):
                                print("✓ Post button is enabled")
                                post_enabled = True
                                break
                        except:
                            pass
                    if post_enabled:
                        break
                    page.wait_for_timeout(500)
                
                # Click Post button
                print("Clicking Post button...")
                
                post_btn = None
                for selector in post_button_selectors:
                    try:
                        post_btn = page.locator(selector).first
                        if post_btn.is_visible(timeout=1000):
                            print(f"✓ Found Post button")
                            break
                        post_btn = None
                    except:
                        continue

                if post_btn:
                    post_btn.click()
                    page.wait_for_timeout(2000)
                    
                    # Check if dialog opened (LinkedIn shows audience selector first)
                    dialog_open = False
                    try:
                        dialog = page.locator('[role="dialog"]').last
                        if dialog.is_visible(timeout=1500):
                            dialog_open = True
                            print("✓ Audience dialog opened")
                    except:
                        pass
                    
                    if dialog_open:
                        # Click "Anyone" if needed
                        try:
                            anyone_btn = page.locator('button:has-text("Anyone")').first
                            if anyone_btn.is_visible(timeout=1000):
                                anyone_btn.click()
                                page.wait_for_timeout(1000)
                        except:
                            pass
                        
                        # Click Done
                        try:
                            done_btn = page.locator('button:has-text("Done")').first
                            if done_btn.is_visible(timeout=1000):
                                done_btn.click()
                                page.wait_for_timeout(2000)
                        except:
                            pass
                        
                        # Click Post again to submit
                        for selector in post_button_selectors:
                            try:
                                final_btn = page.locator(selector).first
                                if final_btn.is_visible(timeout=1000):
                                    final_btn.click()
                                    print("✓ Post submitted")
                                    break
                            except:
                                continue
                    
                    # Wait for confirmation
                    print("Waiting for confirmation...")
                    page.wait_for_timeout(5000)
                    
                    # Check if successful
                    current_url = page.url.lower()
                    if 'feed' in current_url and 'share' not in current_url:
                        print("✓ POST SUCCESSFUL!")
                    else:
                        try:
                            dialog = page.locator('[role="dialog"]').first
                            if not dialog.is_visible(timeout=1000):
                                print("✓ Dialog closed - post submitted")
                            else:
                                print("⚠ Dialog still open")
                        except:
                            print("✓ Post likely submitted")
                else:
                    print("⚠ Could not find Post button automatically")
                    print()
                    print("MANUAL ACTION REQUIRED:")
                    print("  Please click the 'Post' button manually in the browser")
                    print("  Waiting 30 seconds...")
                    for i in range(30):
                        time.sleep(1)
                        if i % 10 == 0:
                            print(f"  Waiting... ({i}/30 seconds)")
                print()
                
                # Take screenshot for record
                try:
                    screenshot_path = self.vault_path / 'Done' / f'LINKEDIN_POST_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png'
                    screenshot_path.parent.mkdir(parents=True, exist_ok=True)
                    page.screenshot(path=str(screenshot_path))
                    logger.info(f"Screenshot saved: {screenshot_path.name}")
                except Exception as e:
                    logger.debug(f"Could not take screenshot: {e}")
                
                browser.close()
                
                return True
                
        except Exception as e:
            print(f"\n✗ Error posting to LinkedIn: {e}")
            return False

    def run(self, auto_mode: bool = False):
        """Main flow: Generate post and submit to LinkedIn.
        
        Args:
            auto_mode: If True, post without confirmation prompt
        """
        print("\n" + "=" * 70)
        print("AI Employee - LinkedIn Auto-Post")
        print("=" * 70)
        print()
        print("Powered by Qwen AI")
        if auto_mode:
            print("Mode: AUTO (no confirmation required)")
        print()

        # Step 1: Generate content
        content = self.generate_post_content()

        # Step 2: Ask for confirmation (unless auto mode)
        if not auto_mode:
            print("Do you want to post this content to LinkedIn?")
            print()
            response = input("Type 'yes' to post, or press Enter to skip: ").strip().lower()

            if response != 'yes':
                print("\nPost cancelled.")
                print(f"Draft saved to: {self.draft_path}")
                return
        else:
            print("Auto mode: Posting directly...")

        # Step 3: Post to LinkedIn
        success = self.post_to_linkedin(content)
        
        # Step 4: Save result
        if success:
            print("\n" + "=" * 70)
            print("✓ POST SUCCESSFUL!")
            print("=" * 70)
            print()
            print("Your LinkedIn post has been submitted.")
            print()
            
            # Save completion record
            result_path = self.vault_path / 'Done' / f'LINKEDIN_POST_{datetime.now().strftime("%Y%m%d_%H%M%S")}.md'
            result_content = f"""---
type: linkedin_post_result
created: {datetime.now().isoformat()}
status: posted
platform: linkedin
---

# LinkedIn Post - Completed

**Posted:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

**Content:**
{content}

---

**Result:** Successfully posted to LinkedIn

**Screenshot:** See Done folder

"""
            result_path.write_text(result_content, encoding='utf-8')
        else:
            print("\n" + "=" * 70)
            print("✗ POST FAILED")
            print("=" * 70)
            print()
            print("The post was not submitted.")
            print("Check the error message above and try again.")


def main():
    """Main entry point."""
    project_root = Path(__file__).parent.parent.absolute()
    vault_path = project_root / 'personal-ai-employee'

    # Parse command line arguments
    auto_mode = '--auto' in sys.argv or '-a' in sys.argv

    poster = LinkedInAutoPost(vault_path)
    poster.run(auto_mode=auto_mode)


if __name__ == '__main__':
    main()
