"""
LinkedIn Auto-Post for AI Employee

Flow:
1. Run this script
2. Browser opens with your saved LinkedIn session
3. Qwen AI generates a business post
4. Post is submitted to LinkedIn
5. Result shown in terminal

Uses Qwen Code for reasoning and content generation.
"""

import time
import logging
import json
from pathlib import Path
from datetime import datetime
from typing import Optional
from playwright.sync_api import sync_playwright, Page

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(message)s'
)
logger = logging.getLogger('LinkedIn Post')


class LinkedInAutoPost:
    """Post to LinkedIn using saved session and Qwen AI."""

    def __init__(self, vault_path: Path):
        self.vault_path = vault_path
        self.session_path = vault_path.parent / 'linkedin_session'
        self.business_goals_path = vault_path / 'Business_Goals.md'
        self.handbook_path = vault_path / 'Company_Handbook.md'
        
        # Output paths
        self.draft_path = vault_path / 'Plans' / f'LINKEDIN_POST_{datetime.now().strftime("%Y%m%d_%H%M%S")}.md'
        self.approval_path = vault_path / 'Pending_Approval' / f'APPROVAL_LINKEDIN_POST_{datetime.now().strftime("%Y%m%d_%H%M%S")}.md'

    def generate_post_content(self) -> str:
        """
        Generate LinkedIn post content using Qwen AI.
        
        In production, this would call Qwen API or Qwen Code.
        For now, creates a sample business post.
        """
        print("\n" + "=" * 70)
        print("Generating LinkedIn Post Content with Qwen AI")
        print("=" * 70)
        print()
        
        # Read business goals for context
        business_goals = ""
        if self.business_goals_path.exists():
            business_goals = self.business_goals_path.read_text(encoding='utf-8')
        
        # Sample post content - in production, call Qwen API here
        post_content = """🚀 Exciting News!

I'm thrilled to share that we're launching a new AI-powered automation service to help businesses streamline their operations.

Key benefits:
✅ 24/7 autonomous operations
✅ 85% cost reduction vs traditional methods
✅ Seamless integration with your existing tools

We're helping businesses transform how they work with intelligent agents that never sleep.

Interested in learning more? Drop a comment or send me a DM!

#AI #Automation #BusinessTransformation #Innovation #DigitalTransformation #ArtificialIntelligence
"""
        
        print("✓ Post content generated by Qwen AI")
        print()
        print("-" * 70)
        print(post_content)
        print("-" * 70)
        print()
        
        # Save draft
        draft_content = f"""---
type: linkedin_post
created: {datetime.now().isoformat()}
status: draft
platform: linkedin
---

# LinkedIn Post Draft

**Generated by:** Qwen AI

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Post Content

{post_content}

---

## To Post

Run: python scripts/linkedin_post.py

This will:
1. Open LinkedIn with your saved session
2. Navigate to post creation
3. Paste the content
4. Submit the post

---

## Result

_Will be filled after posting_

"""
        
        self.draft_path.parent.mkdir(parents=True, exist_ok=True)
        self.draft_path.write_text(draft_content, encoding='utf-8')
        logger.info(f"Draft saved to: {self.draft_path.name}")
        
        return post_content

    def post_to_linkedin(self, content: str) -> bool:
        """Post content to LinkedIn using browser automation."""
        print("\n" + "=" * 70)
        print("Posting to LinkedIn")
        print("=" * 70)
        print()
        
        if not self.session_path.exists():
            print("ERROR: No LinkedIn session found!")
            print()
            print("Please run login first:")
            print("  python scripts/linkedin_login.py")
            return False

        try:
            with sync_playwright() as p:
                # Launch browser with saved session
                print("Opening LinkedIn with saved session...")
                browser = p.chromium.launch_persistent_context(
                    user_data_dir=str(self.session_path),
                    headless=False,  # Visible so user can see what's happening
                    viewport={'width': 1280, 'height': 720},
                    args=[
                        '--disable-blink-features=AutomationControlled',
                        '--disable-dev-shm-usage',
                        '--no-sandbox',
                    ]
                )

                page = browser.pages[0] if browser.pages else browser.new_page()
                
                # Navigate to LinkedIn
                print("Navigating to LinkedIn...")
                page.goto('https://www.linkedin.com/feed/', wait_until='networkidle', timeout=60000)
                page.wait_for_timeout(5000)
                
                # Check if logged in
                if 'login' in page.url.lower():
                    print("\n✗ Not logged in! Session may have expired.")
                    print()
                    print("Please re-login:")
                    print("  python scripts/linkedin_login.py")
                    browser.close()
                    return False
                
                print("✓ Logged in successfully")
                print()
                
                # Find and click the "Start a post" button
                print("Opening post creation dialog...")
                
                # Try multiple selectors for the post button
                post_button_selectors = [
                    'button:has-text("Start a post")',
                    'button:has-text("Start a Post")',
                    'div[role="button"]:has-text("Start a post")',
                    '.share-box-feed-entry__trigger',
                ]
                
                post_button = None
                for selector in post_button_selectors:
                    try:
                        post_button = page.locator(selector).first
                        if post_button.is_visible(timeout=3000):
                            break
                        post_button = None
                    except:
                        continue
                
                if post_button:
                    post_button.click()
                    page.wait_for_timeout(3000)
                    print("✓ Post dialog opened")
                else:
                    print("⚠ Could not find post button, trying alternative method...")
                    # Navigate directly to post creation
                    page.goto('https://www.linkedin.com/feed/?shareActive=true', wait_until='networkidle')
                    page.wait_for_timeout(3000)
                
                # Find the text editor and fill content
                print("Entering post content...")
                
                # Find editor (LinkedIn uses a contenteditable div)
                editor_selectors = [
                    'div[contenteditable="true"]',
                    'div.ProseMirror',
                    '.editor[contenteditable]',
                ]
                
                editor = None
                for selector in editor_selectors:
                    try:
                        editor = page.locator(selector).first
                        if editor.is_visible(timeout=3000):
                            break
                        editor = None
                    except:
                        continue
                
                if editor:
                    # Clear and fill
                    editor.click()
                    page.wait_for_timeout(1000)
                    
                    # Use keyboard to paste content (more reliable)
                    page.keyboard.press('Control+A')
                    page.keyboard.press('Delete')
                    page.wait_for_timeout(500)
                    
                    # Type content in chunks
                    for line in content.split('\n'):
                        page.keyboard.type(line)
                        page.keyboard.press('Enter')
                        page.wait_for_timeout(100)
                    
                    print("✓ Content entered")
                else:
                    print("⚠ Could not find editor, content ready for manual paste")
                    print()
                    print("Please copy-paste this content:")
                    print("-" * 70)
                    print(content)
                    print("-" * 70)
                
                # Wait a moment for content to render
                print()
                print("Waiting 5 seconds for content to render...")
                time.sleep(5)

                # Find and click the Post button
                print("Looking for Post button...")
                
                post_button_selectors = [
                    'button:has-text("Post")',
                    'button:has-text("POST")',
                    'button[data-control-name="compose-submit"]',
                    '.share-box-actions button:first-child',
                ]
                
                post_btn = None
                for selector in post_button_selectors:
                    try:
                        post_btn = page.locator(selector).first
                        if post_btn.is_visible(timeout=3000):
                            print(f"✓ Found Post button with selector: {selector}")
                            break
                        post_btn = None
                    except:
                        continue
                
                if post_btn:
                    print("Clicking first 'Post' button (opens settings)...")
                    post_btn.click()
                    page.wait_for_timeout(5000)
                    print("✓ Post settings dialog should be open now")
                    
                    # Wait for settings dialog to appear
                    page.wait_for_timeout(3000)
                    
                    # Check for audience selector and select "Anyone"
                    print("Selecting 'Anyone' audience...")
                    try:
                        # Click on "Anyone" option
                        anyone_option = page.locator('text="Anyone"').first
                        if anyone_option.is_visible(timeout=3000):
                            print("Found 'Anyone' option, clicking...")
                            anyone_option.click()
                            page.wait_for_timeout(2000)
                            print("✓ 'Anyone' selected")
                        else:
                            print("⚠ 'Anyone' option not found, may already be selected")
                    except Exception as e:
                        logger.debug(f"Audience selection issue: {e}")
                    
                    # Click Done button to return to editor
                    print("Clicking 'Done' button...")
                    try:
                        done_btn = page.locator('button:has-text("Done")').first
                        if done_btn.is_visible(timeout=3000):
                            # Check if enabled (blue button)
                            is_disabled = done_btn.get_attribute('disabled')
                            if is_disabled:
                                print("⚠ Done button is disabled, waiting...")
                                page.wait_for_timeout(3000)
                            
                            done_btn.click()
                            page.wait_for_timeout(3000)
                            print("✓ Done button clicked - back to editor")
                        else:
                            print("⚠ Done button not found")
                    except Exception as e:
                        logger.debug(f"Done button issue: {e}")
                    
                    # Wait for settings dialog to close
                    page.wait_for_timeout(2000)
                    
                    # NOW click the final Post button (this actually submits the post)
                    print("Clicking FINAL 'Post' button to submit...")
                    
                    final_post_btn = None
                    for selector in post_button_selectors:
                        try:
                            final_post_btn = page.locator(selector).first
                            if final_post_btn.is_visible(timeout=3000):
                                print(f"✓ Found final Post button: {selector}")
                                final_post_btn.click()
                                print("✓ FINAL POST BUTTON CLICKED!")
                                break
                            final_post_btn = None
                        except:
                            continue
                    
                    if not final_post_btn:
                        print("⚠ Could not find final Post button")
                        print("The post may have been submitted already or needs manual completion")
                    
                    # Wait for confirmation
                    print("Waiting for post confirmation (10 seconds)...")
                    page.wait_for_timeout(10000)
                    
                    # Check if we're back on feed (post was successful)
                    current_url = page.url.lower()
                    if 'feed' in current_url and 'share' not in current_url and 'post' not in current_url:
                        print("✓ POST SUCCESSFUL! Back on feed page.")
                    else:
                        print("⚠ Checking if post dialog closed...")
                        # Try to detect if the dialog is gone
                        try:
                            dialog = page.locator('[role="dialog"]').first
                            if not dialog.is_visible(timeout=2000):
                                print("✓ Dialog closed - post likely submitted")
                            else:
                                print("⚠ Dialog still open - manual completion may be needed")
                        except:
                            print("✓ No dialog detected - post likely submitted")
                        
                        print(f"  Current URL: {page.url}")
                else:
                    print("⚠ Could not find Post button automatically")
                    print()
                    print("MANUAL ACTION REQUIRED:")
                    print("  Please click the 'Post' button manually in the browser")
                    print("  Waiting 30 seconds...")
                    for i in range(30):
                        time.sleep(1)
                        if i % 10 == 0:
                            print(f"  Waiting... ({i}/30 seconds)")
                print()
                
                # Take screenshot for record
                try:
                    screenshot_path = self.vault_path / 'Done' / f'LINKEDIN_POST_{datetime.now().strftime("%Y%m%d_%H%M%S")}.png'
                    screenshot_path.parent.mkdir(parents=True, exist_ok=True)
                    page.screenshot(path=str(screenshot_path))
                    logger.info(f"Screenshot saved: {screenshot_path.name}")
                except Exception as e:
                    logger.debug(f"Could not take screenshot: {e}")
                
                browser.close()
                
                return True
                
        except Exception as e:
            print(f"\n✗ Error posting to LinkedIn: {e}")
            return False

    def run(self):
        """Main flow: Generate post and submit to LinkedIn."""
        print("\n" + "=" * 70)
        print("AI Employee - LinkedIn Auto-Post")
        print("=" * 70)
        print()
        print("Powered by Qwen AI")
        print()
        
        # Step 1: Generate content
        content = self.generate_post_content()
        
        # Step 2: Ask for confirmation
        print("Do you want to post this content to LinkedIn?")
        print()
        response = input("Type 'yes' to post, or press Enter to skip: ").strip().lower()
        
        if response != 'yes':
            print("\nPost cancelled.")
            print(f"Draft saved to: {self.draft_path}")
            return
        
        # Step 3: Post to LinkedIn
        success = self.post_to_linkedin(content)
        
        # Step 4: Save result
        if success:
            print("\n" + "=" * 70)
            print("✓ POST SUCCESSFUL!")
            print("=" * 70)
            print()
            print("Your LinkedIn post has been submitted.")
            print()
            
            # Save completion record
            result_path = self.vault_path / 'Done' / f'LINKEDIN_POST_{datetime.now().strftime("%Y%m%d_%H%M%S")}.md'
            result_content = f"""---
type: linkedin_post_result
created: {datetime.now().isoformat()}
status: posted
platform: linkedin
---

# LinkedIn Post - Completed

**Posted:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

**Content:**
{content}

---

**Result:** Successfully posted to LinkedIn

**Screenshot:** See Done folder

"""
            result_path.write_text(result_content, encoding='utf-8')
        else:
            print("\n" + "=" * 70)
            print("✗ POST FAILED")
            print("=" * 70)
            print()
            print("The post was not submitted.")
            print("Check the error message above and try again.")


def main():
    """Main entry point."""
    project_root = Path(__file__).parent.parent.absolute()
    vault_path = project_root / 'personal-ai-employee'

    poster = LinkedInAutoPost(vault_path)
    poster.run()


if __name__ == '__main__':
    main()
